# Generated by Django 6.0.1 on 2026-02-22 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('schools', '0040_alter_competencycomment_education_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['-year', 'vote_head']},
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='term',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='applicable_classes',
            field=models.ManyToManyField(related_name='fee_structures', to='schools.classroom'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='applied_terms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='billing_mode',
            field=models.CharField(choices=[('ONCE_YEAR', 'Once a year'), ('SELECTED_TERMS', 'Selected terms')], default='SELECTED_TERMS', max_length=20),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='due_term',
            field=models.CharField(blank=True, choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=20),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='vote_head',
            field=models.CharField(default='General', max_length=120),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='schools.school'),
        ),
    ]
