# Generated by Codex on 2026-03-14
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_expenditure_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='mpesa_code',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='bank_slip_no',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='cheque_no',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
