# Generated by Django 6.0.1 on 2026-01-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='short_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_subject_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_subject_name_per_school'),
        ),
    ]
