# Generated by Django 6.0.1 on 2026-01-31 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_teacherassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectallocation',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.classroom'),
        ),
    ]
