# Generated by Django 6.0.1 on 2026-01-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_subjectallocation_admission_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectallocation',
            name='student_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
