# Generated by Django 6.0.1 on 2026-02-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_alter_classroom_options_classroom_order_promotionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_alumni',
            field=models.BooleanField(default=False),
        ),
    ]
