# Generated by assistant: add school FK to Exam
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='schools.school'),
        ),
    ]
