# Generated by assistant: make Exam.school non-nullable
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_add_exam_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(to='schools.School', on_delete=models.CASCADE, related_name='exams'),
        ),
    ]
