# Generated by Django 6.0.1 on 2026-02-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_alter_exam_school_termdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termdate',
            options={'ordering': ['-year', 'term']},
        ),
    ]
