# Generated by Django 6.0.1 on 2026-02-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0022_add_termdate_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SkulPlus', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_logo/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.AlterModelOptions(
            name='termdate',
            options={},
        ),
    ]
