# Generated by Django 6.0.1 on 2026-02-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_siteconfig_alter_termdate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='head_signature',
            field=models.ImageField(blank=True, null=True, upload_to='head_signatures/'),
        ),
        migrations.AddField(
            model_name='school',
            name='stamp',
            field=models.ImageField(blank=True, null=True, upload_to='school_stamps/'),
        ),
    ]
