# Generated by Django 6.0.1 on 2026-02-05 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0027_alter_classroom_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_teacher_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_as_class_teacher_stream', to='schools.stream'),
        ),
    ]
