# Generated by Django 6.0.1 on 2026-02-05 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0028_classroom_class_teacher_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='class_teacher_stream',
        ),
        migrations.CreateModel(
            name='StreamClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_class_teachers', to='schools.classroom')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.stream')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.teacher')),
            ],
            options={
                'unique_together': {('classroom', 'stream')},
            },
        ),
    ]
