# Generated by ChatGPT on 2026-02-06
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0030_cbe_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_subjects', to='schools.educationlevel'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='pathway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_subjects', to='schools.pathway'),
        ),
    ]
