# Generated by Django 6.0.1 on 2026-02-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0034_school_motto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
