# Generated by Django 6.0.1 on 2026-02-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0039_studentmark_comment_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencycomment',
            name='education_level',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Lower Primary', 'Lower Primary'), ('Upper Primary', 'Upper Primary'), ('Junior', 'Junior')], max_length=20),
        ),
    ]
