# Generated by ChatGPT on 2026-02-06
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject_school_exam_mark_exam_and_more'),
        ('schools', '0030_cbe_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='pathway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.pathway'),
        ),
        migrations.AddField(
            model_name='subject',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.educationlevel'),
        ),
        migrations.CreateModel(
            name='StudentPathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schools.student')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.pathway')),
            ],
        ),
    ]
