# Generated by ChatGPT on 2026-03-12
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0054_attendance_registers'),
        ('academics', '0004_subject_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('curriculum_type', models.CharField(choices=[('CBE', 'CBE'), ('CAMBRIDGE', 'Cambridge')], max_length=20)),
                ('document', models.FileField(upload_to='syllabus_docs/')),
                ('sample_scheme', models.FileField(blank=True, null=True, upload_to='syllabus_docs/')),
                ('sample_lesson_plan', models.FileField(blank=True, null=True, upload_to='syllabus_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.classroom')),
                ('education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.educationlevel')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
